(function() {function f(a){throw a;}var h=void 0,k=!0,l=null,o=!1;function q(a){return function(){return this[a]}}function v(a){return function(){return a}}var w,x=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function y(a){return a!==h}function ba(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function z(a){return"string"==typeof a}function ca(a){return"number"==typeof a}Math.floor(2147483648*Math.random()).toString(36);function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return A.apply(l,arguments)}function fa(a,b){function c(){}c.prototype=b.prototype;a.qc=b.prototype;a.prototype=new c};function C(a,b,c){this.type=a;this.T=b;this.Ha=c};function ga(a){a=""+a;if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}function ha(){this.Za=h}
function ia(a,b,c){switch(typeof b){case "string":ja(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if("array"==aa(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],ia(a,a.Za?a.Za.call(b,""+g,e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&(c.push(d),ja(g,
c),c.push(":"),ia(a,a.Za?a.Za.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var ka={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},la=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ja(a,b){b.push('"',a.replace(la,function(a){if(a in ka)return ka[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ka[a]=e+b.toString(16)}),'"')};function ma(a){if("undefined"!==typeof JSON&&y(JSON.stringify))a=JSON.stringify(a);else{var b=[];ia(new ha,a,b);a=b.join("")}return a};function D(a,b){this.na=a?a:na;this.J=b?b:oa}function na(a,b){return a<b?-1:a>b?1:0}w=D.prototype;w.P=function(a,b){return new D(this.na,this.J.P(a,b,this.na).copy(l,l,o,l,l))};w.remove=function(a){return new D(this.na,this.J.remove(a,this.na).copy(l,l,o,l,l))};w.get=function(a){for(var b,c=this.J;!c.a();){b=this.na(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return l};
function pa(a,b){for(var c,d=a.J,e=l;!d.a();){c=a.na(b,d.key);if(0===c){if(d.left.a())return e?e.key:l;for(d=d.left;!d.right.a();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}f("Attempted to find predecessor key for a nonexistent key.  What gives?")}w.a=function(){return this.J.a()};w.count=function(){return this.J.count()};w.Ba=function(){return this.J.Ba()};w.sa=function(){return this.J.sa()};w.W=function(a){return this.J.W(a)};w.fa=function(a){return this.J.fa(a)};
w.qa=function(a){return new qa(this.J,a)};function qa(a,b){this.Fb=b;for(this.Qa=[];!a.a();)this.Qa.push(a),a=a.left}function sa(a){if(0===a.Qa.length)return l;var b=a.Qa.pop(),c;c=a.Fb?a.Fb(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.a();)a.Qa.push(b),b=b.left;return c}function ta(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=l?c:k;this.left=d!=l?d:oa;this.right=e!=l?e:oa}w=ta.prototype;
w.copy=function(a,b,c,d,e){return new ta(a!=l?a:this.key,b!=l?b:this.value,c!=l?c:this.color,d!=l?d:this.left,e!=l?e:this.right)};w.count=function(){return this.left.count()+1+this.right.count()};w.a=v(o);w.W=function(a){return this.left.W(a)||a(this.key,this.value)||this.right.W(a)};w.fa=function(a){return this.right.fa(a)||a(this.key,this.value)||this.left.fa(a)};function ua(a){return a.left.a()?a:ua(a.left)}w.Ba=function(){return ua(this).key};w.sa=function(){return this.right.a()?this.key:this.right.sa()};
w.P=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(l,l,l,e.left.P(a,b,c),l):0===d?e.copy(l,b,l,l,l):e.copy(l,l,l,l,e.right.P(a,b,c));return va(e)};function wa(a){if(a.left.a())return oa;!a.left.m()&&!a.left.left.m()&&(a=xa(a));a=a.copy(l,l,l,wa(a.left),l);return va(a)}
w.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.a()&&!c.left.m()&&!c.left.left.m()&&(c=xa(c)),c=c.copy(l,l,l,c.left.remove(a,b),l);else{c.left.m()&&(c=ya(c));!c.right.a()&&!c.right.m()&&!c.right.left.m()&&(c=za(c),c.left.left.m()&&(c=ya(c),c=za(c)));if(0===b(a,c.key)){if(c.right.a())return oa;d=ua(c.right);c=c.copy(d.key,d.value,l,l,wa(c.right))}c=c.copy(l,l,l,l,c.right.remove(a,b))}return va(c)};w.m=q("color");
function va(a){a.right.m()&&!a.left.m()&&(a=Aa(a));a.left.m()&&a.left.left.m()&&(a=ya(a));a.left.m()&&a.right.m()&&(a=za(a));return a}function xa(a){a=za(a);a.right.left.m()&&(a=a.copy(l,l,l,l,ya(a.right)),a=Aa(a),a=za(a));return a}function Aa(a){return a.right.copy(l,l,a.color,a.copy(l,l,k,l,a.right.left),l)}function ya(a){return a.left.copy(l,l,a.color,l,a.copy(l,l,k,a.left.right,l))}
function za(a){var b,c;b=a.left.copy(l,l,!a.left.color,l,l);c=a.right.copy(l,l,!a.right.color,l,l);return a.copy(l,l,!a.color,b,c)}function Ba(){}w=Ba.prototype;w.copy=function(){return this};w.P=function(a,b){return new ta(a,b,h,h,h)};w.remove=function(){return this};w.get=v(l);w.count=v(0);w.a=v(k);w.W=v(o);w.fa=v(o);w.Ba=v(l);w.sa=v(l);w.m=v(o);var oa=new Ba;var Ca=/^[a-zA-Z0-9\-_.!~*'()]*$/;function Da(a){a=""+a;return!Ca.test(a)?encodeURIComponent(a):a};function E(a){if(a instanceof E)return a;if(1==arguments.length){this.g=a.split("/");for(var b=0,c=0;c<this.g.length;c++)0<this.g[c].length&&(this.g[b]=this.g[c],b++);this.g.length=b;this.I=0}else this.g=arguments[0],this.I=arguments[1]}function H(a){return a.I>=a.g.length?l:a.g[a.I]}function I(a){var b=a.I;b<a.g.length&&b++;return new E(a.g,b)}function Ea(a){return a.I<a.g.length?a.g[a.g.length-1]:l}
E.prototype.toString=function(){for(var a="",b=this.I;b<this.g.length;b++)""!==this.g[b]&&(a+="/"+this.g[b]);return a};E.prototype.parent=function(){if(this.I>=this.g.length)return l;for(var a=[],b=this.I;b<this.g.length-1;b++)a.push(this.g[b]);return new E(a,0)};E.prototype.k=function(a){for(var b=[],c=this.I;c<this.g.length;c++)b.push(this.g[c]);if(a instanceof E)for(c=a.I;c<a.g.length;c++)b.push(a.g[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new E(b,0)};
E.prototype.a=function(){return this.I>=this.g.length};function Fa(a,b){var c=H(a);if(c===l)return b;if(c===H(b))return Fa(I(a),I(b));f("INTERNAL ERROR: innerParsedPath ("+b+") is not within outerParsedPath ("+a+")")};function Ga(a,b){this.ma=a;this.va="undefined"!==typeof b?b:l}w=Ga.prototype;w.Q=v(k);w.f=q("va");w.eb=function(a){return new Ga(this.ma,a)};w.t=function(){return J};w.e=function(a){return H(a)===l?this:J};w.G=v(l);w.p=function(a,b){return(new K(new D,this.va)).p(a,b)};w.wa=function(a,b){var c=H(a);return c===l?b:this.p(c,J.wa(I(a),b))};w.a=v(o);w.w=function(a){return a&&this.f()!==l?{".value":this.c(),".priority":""+this.f()}:this.c()};
w.hash=function(){var a="";this.f()!==l&&(a+="priority:"+this.f()+":");a+=typeof this.ma+":"+this.ma;return Ha(a)};w.c=q("ma");w.toString=function(){return"string"===typeof this.ma?'"'+this.ma+'"':this.ma};function K(a,b){this.D=a||new D;this.va="undefined"!==typeof b?b:l}w=K.prototype;w.Q=v(o);w.f=q("va");w.eb=function(a){return new K(this.D,a)};w.p=function(a,b){var c=this.D.remove(a);b&&b.a()&&(b=l);b!==l&&(c=c.P(a,b));return b&&b.f()!==l?new Ia(c,l,this.va):new K(c,this.va)};
w.wa=function(a,b){var c=H(a);if(c===l)return b;var d=this.t(c).wa(I(a),b);return this.p(c,d)};w.a=function(){return this.D.a()};var Ja=/^\d+$/;w=K.prototype;w.w=function(a){if(this.a())return l;var b={},c=0,d=0,e=k;this.o(function(g,i){b[g]=i.w(a);c++;e&&Ja.test(g)?d=Math.max(d,Number(g)):e=o});if(!a&&e&&d<2*c){var g=[],i;for(i in b)g[i]=b[i];return g}a&&this.f()!==l&&(b[".priority"]=""+this.f());return b};
w.hash=function(){var a="";this.f()!==l&&(a+="priority:"+this.f()+":");this.o(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Ha(a)};w.t=function(a){a=this.D.get(a);return a===l?J:a};w.e=function(a){var b=H(a);return b===l?this:this.t(b).e(I(a))};w.G=function(a){return pa(this.D,a)};w.wb=function(){return this.D.Ba()};w.yb=function(){return this.D.sa()};w.o=function(a){return this.D.W(a)};w.ib=function(a){return this.D.fa(a)};w.qa=function(){return this.D.qa()};
w.toString=function(){var a="{",b=k;this.o(function(c,d){b?b=o:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var J=new K(new D);function Ia(a,b,c){K.call(this,a,c);b===l&&(b=new D(Ka),a.W(function(a,c){b=b.P({name:a,ea:c.f()},c)}));this.ia=b}fa(Ia,K);w=Ia.prototype;w.p=function(a,b){var c=this.t(a),d=this.D,e=this.ia;c!==l&&(d=d.remove(a),e=e.remove({name:a,ea:c.f()}));b&&b.a()&&(b=l);b!==l&&(d=d.P(a,b),e=e.P({name:a,ea:b.f()},b));return new Ia(d,e,this.f())};
w.G=function(a,b){var c=pa(this.ia,{name:a,ea:b.f()});return c?c.name:l};w.o=function(a){return this.ia.W(function(b,c){return a(b.name,c)})};w.ib=function(a){return this.ia.fa(function(b,c){return a(b.name,c)})};w.qa=function(){return this.ia.qa(function(a,b){return{key:a.name,value:b}})};w.wb=function(){return this.ia.Ba().name};w.yb=function(){return this.ia.sa().name};
function La(a,b){if("object"!==typeof a)return new Ga(a,b);if(a===l)return J;var c=".priority"in a?a[".priority"]:b||l;c!==l&&(c=Ma.test(c)?Number(c):c);if(".value"in a&&a[".value"]!==l)return new Ga(a[".value"],c);var c=new K(new D,c),d;for(d in a)if("."!==d.substring(0,1)){var e=La(a[d]);if(e.Q()||!e.a())c=c.p(d,e)}return c}function Ka(a,b){return Na(a.ea,b.ea)||(a.name!==b.name?a.name<b.name?-1:1:0)};function Oa(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};var Pa=/[\[\].#$\/]/,Qa=/[\[\].#$]/;function Ra(a){return z(a)&&0!==a.length&&!Pa.test(a)}function L(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&f(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function Sa(a,b,c){(!c||y(b))&&Ta(M(a,1,c),b)}
function Ta(a,b){y(b)||f(Error(a+"contains undefined."));"function"==aa(b)&&f(Error(a+"contains a function."));z(b)&&b.length>10485760/3&&10485760<Oa(b).length&&f(Error(a+"contains a string greater than 10485760 utf8 bytes ('"+b.substring(0,50)+"...')"));var c=aa(b);if("object"==c||"array"==c||"function"==c)for(var d in b)".priority"!==d&&".value"!==d&&!Ra(d)&&f(Error(a+"contains an invalid key ("+d+').  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),Ta(a,b[d])}
function Ua(a,b,c,d){(!d||y(c))&&c!==l&&!ca(c)&&!z(c)&&f(Error(M(a,b,d)+"must be a valid firebase priority (null or a string.)"))}function N(a,b,c,d){(!d||y(c))&&"function"!=aa(c)&&f(Error(M(a,b,d)+"must be a valid function."))}function Va(a,b){switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:f(Error(M(a,1,o)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}
function Wa(a,b){y(b)&&!Ra(b)&&f(Error(M(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}function Xa(a,b){(!z(b)||0===b.length||Qa.test(b))&&f(Error(M(a,1,o)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}
function M(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:O(o,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}a+=" failed: ";c&&(a+="If provided, ");return a+(d+" argument ")};function P(a,b){this.b=a;this.Ya=b}P.prototype.w=function(){L("Firebase.DataSnapshot.val",0,0,arguments.length);return this.b.w()};P.prototype.val=P.prototype.w;P.prototype.Nb=function(){L("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.b.w(k)};P.prototype.exportVal=P.prototype.Nb;P.prototype.k=function(a){L("Firebase.DataSnapshot.child",0,1,arguments.length);ca(a)&&(a=""+a);Xa("Firebase.DataSnapshot.child",a);var b=new E(a),c=this.Ya.k(b);return new P(this.b.e(b),c)};
P.prototype.child=P.prototype.k;P.prototype.Ob=function(a){L("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Xa("Firebase.DataSnapshot.hasChild",a);return!this.b.e(new E(a)).a()};P.prototype.hasChild=P.prototype.Ob;P.prototype.f=function(){L("Firebase.DataSnapshot.getPriority",0,0,arguments.length);var a=this.b.f();return a===l?a:""+a};P.prototype.getPriority=P.prototype.f;
P.prototype.forEach=function(a){L("Firebase.DataSnapshot.forEach",1,1,arguments.length);N("Firebase.DataSnapshot.forEach",1,a,o);if(this.b.Q())return o;var b=this;return this.b.o(function(c,d){return a(new P(d,b.Ya.k(c)))})};P.prototype.forEach=P.prototype.forEach;P.prototype.Na=function(){L("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.b.Q()?o:!this.b.a()};P.prototype.hasChildren=P.prototype.Na;
P.prototype.name=function(){L("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Ya.name()};P.prototype.name=P.prototype.name;P.prototype.gc=function(){L("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Ya};P.prototype.ref=P.prototype.gc;function Ya(a){for(var b in a)return o;return k};function Za(){this.children={};this.Ka=0;this.value=l}function Q(a,b,c){this.Pa=a?a:"";this.Fa=b?b:l;this.b=c?c:new Za}function R(a,b){for(var c=b instanceof E?b:new E(b),d=a,e;(e=H(c))!==l;)d=new Q(e,d,e in d.b.children?d.b.children[e]:new Za),c=I(c);return d}w=Q.prototype;w.c=function(){return this.b.value};function S(a,b){a.b.value=b;$a(a)}w.clear=function(){this.b.value=l;this.b.children={};this.b.Ka=0;$a(this)};w.Na=function(){return 0<this.b.Ka};w.a=function(){return this.c()===l&&!this.Na()};
w.o=function(a){for(var b in this.b.children)a(new Q(b,this,this.b.children[b]))};function ab(a,b){a.o(function(c){b(new Q(c.name(),a,a.b.children[c.name()]));ab(c,b)})}function bb(a,b,c){for(a=c?a:a.parent();a!==l;)b(a),a=a.parent()}function cb(a,b){a.o(function(a){a.c()!==l?b(a):cb(a,b)})}function T(a,b){for(var c=a.b;c;){if(c.value!==l)return k;c=c.children[H(b)];b=I(b)}}w.path=function(){return new E(this.Fa===l?this.Pa:this.Fa.path()+"/"+this.Pa)};w.name=q("Pa");w.parent=q("Fa");
function $a(a){if(a.Fa!==l){var b=a.Fa,c=a.Pa,d=a.a(),e=c in b.b.children;d&&e?(delete b.b.children[c],b.b.Ka--,$a(b)):!d&&!e&&(b.b.children[c]=a.b,b.b.Ka++,$a(b))}};function db(){this.set={}}w=db.prototype;w.add=function(a,b){this.set[a]=b!==l?b:k};w.get=function(a){return this.set[a]};w.remove=function(a){delete this.set[a]};w.clear=function(){this.set={}};w.a=function(){for(var a in this.set)return o;return k};w.count=function(){var a=0,b;for(b in this.set)a++;return a};var eb="pLPCommand",fb="pRTLPCB";
function gb(a,b,c,d,e){this.Ca="http://"+a;this.tb=0;this.v=d;this.Vb=new hb(b);var g=this;this.aa=setTimeout(function(){U("Timed out trying to connect.");g.close();g.aa=l},3E4);ib(function(){if(!this.Oa){g.ga=new jb(function(a,b,d){if(g.ga)if(g.aa&&(clearTimeout(g.aa),g.aa=l),"start"==a){c();a=g.ga;a.Tb=b;a.Ub=d;for(a.fb=k;kb(a););g.ta=document.createElement("iframe");g.ta.src=g.Ca+"?disconn=t&id="+b+"&pw="+d;g.ta.style.display="none";document.body.appendChild(g.ta)}else"reset"==a?(U("Got Server RESET packet."),
g.close()):"shutdown"==a&&(U("Shutdown message received from server, likely due to unmatching version numbers."),e())},function(a,b){var c=g.Vb;for(c.Ua[a]=b;c.Ua[c.La];){var d=c.Ua[c.La];delete c.Ua[c.La];for(var e=0;e<d.length;e++)d[e]&&c.Sb(d[e]);c.La++}},function(){g.close()},g.Ca);var a=g.Ca+"?start=t&ser="+Math.floor(1E8*Math.random())+"&v=1";U("Connecting via long-poll to "+a);lb(g.ga,a,function(){})}})}
gb.prototype.close=function(){if(!this.Oa&&(this.Oa=k,U("Closing long-poll connection."),this.ga&&(this.ga.close(),this.ga=l),this.ta&&(document.body.removeChild(this.ta),this.ta=l),this.v&&(this.v(),this.v=l),this.aa))clearTimeout(this.aa),this.aa=l};gb.prototype.send=function(a){for(var a=ma(a),a=mb(Oa(a),k),a=nb(a,1840),b=0;b<a.length;b++){var c=this.ga;c.Ga.push({kc:this.tb,oc:a.length,ub:a[b]});c.fb&&kb(c);this.tb++}};function hb(a){this.Sb=a;this.Ua=[];this.La=0}
function jb(a,b,c,d){this.Ca=d;this.v=c;this.ob=new db;this.Ga=[];this.hb=Math.floor(1E8*Math.random());c=ob();window[eb+c]=a;window[fb+c]=b;a=document.createElement("iframe");a.style.display="none";document.body?document.body.appendChild(a):f("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");a.contentDocument?a.V=a.contentDocument:a.contentWindow?a.V=a.contentWindow.document:a.document&&(a.V=a.document);this.R=a;a="<html><body><script>\nfunction "+
eb+'(c, a1, a2, a3, a4) {\nparent.window["'+eb+c+'"](c, a1, a2, a3, a4);\n}\nfunction '+fb+'(pN, data) {\nparent.window["'+fb+c+'"](pN, data);\n}\n<\/script></body></html>\n';this.R.V.open();this.R.V.write(a);this.R.V.close()}jb.prototype.close=function(){this.fb=o;this.R&&(this.R.V.body.innerHTML="",document.body.removeChild(this.R),this.R=l);var a=this.v;a&&(this.v=l,a())};
function kb(a){if(a.fb&&a.ob.count()<(0<a.Ga.length?2:1)){a.hb++;for(var b=a.Ca+"?id="+a.Tb+"&pw="+a.Ub+"&ser="+a.hb,c="",d=0;0<a.Ga.length;)if(1870>=a.Ga[0].ub.length+30+c.length){var e=a.Ga.shift(),c=c+"&seg"+d+"="+e.kc+"&ts"+d+"="+e.oc+"&d"+d+"="+e.ub;d++}else break;rb(a,b+c,a.hb);return k}return o}function rb(a,b,c){function d(){a.ob.remove(c);kb(a)}a.ob.add(c);var e=setTimeout(d,25E3);lb(a,b,function(){clearTimeout(e);d()})}
function lb(a,b,c){setTimeout(function(){try{var d=a.R.V.createElement("script");d.type="text/javascript";d.async=k;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=l,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){U("Long-poll script failed to load.");a.close()};a.R.V.body.appendChild(d)}catch(e){}},1)}
function nb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c};var sb=l;"undefined"!==typeof MozWebSocket?sb=MozWebSocket:"undefined"!==typeof WebSocket&&(sb=WebSocket);
function tb(a,b,c,d,e){this.v=d;this.Ra=b;this.Zb=e;this.cc=c;this.za=l;this.state=0;this.frames=l;this.Jb=0;U("Connecting to ws://"+a);this.A=new sb("ws://"+a);var g=this;this.A.onopen=function(){U("Websocket connected.  Sending hello.");g.A.send("version=1")};this.A.onclose=function(){U("Websocket connection was disconnected.");g.A=l;g.close(k)};this.A.onmessage=function(a){a=a.data;0===g.state?"ok"===a?(U("Got hello packet.  WebSocket good."),g.state=1,g.cc()):"kill"===a&&(U("Shutdown message received from server, likely due to unmatching version numbers."),
g.Zb()):1===g.state?(g.Jb=Number(a),g.state=2,g.frames=[]):2===g.state&&(g.frames.push(a),g.frames.length==g.Jb&&(a="undefined"!==typeof JSON&&y(JSON.parse)?JSON.parse(g.frames.join("")):ga(g.frames.join("")),g.state=1,ub(g),g.Ra(a)))};this.A.onerror=function(){U("WebSocket error.  Closing connection.");g.close()}}tb.prototype.send=function(a){ub(this);a=ma(a);a=nb(a,16384);this.A.send(""+a.length);for(var b=0;b<a.length;b++)this.A.send(a[b])};
tb.prototype.close=function(a){if(!this.Oa&&(this.Oa=k,a||U("Closing WebSocket."),this.za&&(clearTimeout(this.za),this.za=l),this.A&&(this.A.close(),this.A=l),this.v))this.v(),this.v=l};function ub(a){clearTimeout(a.za);a.za=setInterval(function(){a.A.send("0");ub(a)},45E3)};function vb(a,b,c,d,e){this.sb=a;this.Da=b;this.L=c;this.H=d;this.ua=e;this.u=0;this.Aa=l;this.z=0;this.Ja=l;if(sb!==l){U("CHOOSER: Starting WebSocket connection.");O(sb!==l,"WebSocket isn't supported.");O(0===this.z,"webSocketState should be START.");O(2!==this.u,"longPollState should not be CONNECTED");this.z=1;try{this.Ja=new tb(this.sb,this.Da,A(this.dc,this),A(this.ec,this),this.ua)}catch(g){wb("WebSocket constructor threw exception: "+g.toString()),xb(this)}}else xb(this);if(3!==this.z){U("CHOOSER: Trying long-poll connection in 450ms.");
var i=this;setTimeout(function(){yb(i)},450)}else yb(this)}w=vb.prototype;w.dc=function(){U("CHOOSER: WebSocket connection connected.");1===this.z||wb("webSocketState should be CONNECTING.");2===this.u?xb(this):(this.z=2,zb(this),this.L&&(this.L(this.Ja),this.L=l))};w.ec=function(){U("CHOOSER: WebSocket connection disconnected.");O(0!==this.z,"webSocketState should not be START.");O(3===this.u||2!==this.z,"Was CONNECTED via websocket, but long-polling wasn't canceled.");xb(this)};
function yb(a){0===a.u&&(U("CHOOSER: Starting Long-polling connection."),O(k,"Long-polling isn't supported."),O(2!==a.z,"webSocketState should not be CONNECTED."),a.u=1,a.Aa=new gb(a.sb,a.Da,A(a.$b,a),A(a.ac,a),a.ua))}w.$b=function(){U("CHOOSER: Long-polling connection connected.");1===this.u||wb("longPollState should be CONNECTING.");2===this.z?zb(this):(this.u=2,xb(this),this.L&&(this.L(this.Aa),this.L=l))};
w.ac=function(){U("CHOOSER: Long-polling connection disconnected.");O(0!==this.u,"longPollState should not be START.");O(3===this.z||2!==this.u,"Was CONNECTED via long-polling, but websocket wasn't canceled.");zb(this)};function zb(a){3!==a.u&&(U("CHOOSER: Canceling long-polling connection."),a.u=3,a.Aa&&(a.Aa.close(),a.Aa=l),Ab(a))}function xb(a){3!==a.z&&(U("CHOOSER: Canceling websocket connection."),a.z=3,a.Ja&&(a.Ja.close(),a.Ja=l),0===a.u&&yb(a),Ab(a))}
function Ab(a){3===a.z&&3===a.u&&a.H&&(U("CHOOSER: Both websocket and long-polling were canceled.  Connection lost."),a.H(),a.H=l)}w.close=function(){zb(this);xb(this);this.H&&(this.H(),this.H=l)};function Bb(){};function Cb(){this.h=[];this.gb=[];this.Lb=[];this.Ta=[];this.Ta[0]=128;for(var a=1;64>a;++a)this.Ta[a]=0;this.reset()}fa(Cb,Bb);Cb.prototype.reset=function(){this.h[0]=1732584193;this.h[1]=4023233417;this.h[2]=2562383102;this.h[3]=271733878;this.h[4]=3285377520;this.rb=this.ya=0};
function Db(a,b){var c;c||(c=0);for(var d=a.Lb,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var g=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(g<<1|g>>>31)&4294967295}c=a.h[0];for(var i=a.h[1],j=a.h[2],n=a.h[3],m=a.h[4],r,e=0;80>e;e++)40>e?20>e?(g=n^i&(j^n),r=1518500249):(g=i^j^n,r=1859775393):60>e?(g=i&j|n&(i|j),r=2400959708):(g=i^j^n,r=3395469782),g=(c<<5|c>>>27)+g+m+r+d[e]&4294967295,m=n,n=j,j=(i<<30|i>>>2)&4294967295,i=c,c=g;a.h[0]=a.h[0]+c&4294967295;a.h[1]=a.h[1]+i&
4294967295;a.h[2]=a.h[2]+j&4294967295;a.h[3]=a.h[3]+n&4294967295;a.h[4]=a.h[4]+m&4294967295}Cb.prototype.update=function(a,b){y(b)||(b=a.length);var c=this.gb,d=this.ya,e=0;if(z(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(Db(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(Db(this,c),d=0);this.ya=d;this.rb+=b};var Eb,Fb,Gb,Hb;function Ib(){return x.navigator?x.navigator.userAgent:l}Hb=Gb=Fb=Eb=o;var Jb;if(Jb=Ib()){var Kb=x.navigator;Eb=0==Jb.indexOf("Opera");Fb=!Eb&&-1!=Jb.indexOf("MSIE");Gb=!Eb&&-1!=Jb.indexOf("WebKit");Hb=!Eb&&!Gb&&"Gecko"==Kb.product}var Lb=Fb,Mb=Hb,Nb=Gb;var Ob;if(Eb&&x.opera){var Pb=x.opera.version;"function"==typeof Pb&&Pb()}else Mb?Ob=/rv\:([^\);]+)(\)|;)/:Lb?Ob=/MSIE\s+([^\);]+)(\)|;)/:Nb&&(Ob=/WebKit\/(\S+)/),Ob&&Ob.exec(Ib());var Qb=l,Rb=l;
function mb(a,b){ba(a)||f(Error("encodeByteArray takes an array as a parameter"));if(!Qb){Qb={};Rb={};for(var c=0;65>c;c++)Qb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Rb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Rb:Qb,d=[],e=0;e<a.length;e+=3){var g=a[e],i=e+1<a.length,j=i?a[e+1]:0,n=e+2<a.length,m=n?a[e+2]:0,r=g>>2,g=(g&3)<<4|j>>4,j=(j&15)<<2|m>>6,m=m&63;n||(m=64,i||(j=64));d.push(c[r],c[g],c[j],c[m])}return d.join("")}
;var ob=function(){var a=1;return function(){return a++}}();function O(a,b){a||f(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Ha(a){var b=Oa(a),a=new Cb;a.update(b);var b=[],c=8*a.rb;56>a.ya?a.update(a.Ta,56-a.ya):a.update(a.Ta,64-(a.ya-56));for(var d=63;56<=d;d--)a.gb[d]=c&255,c/=256;Db(a,a.gb);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.h[d]>>e&255;return mb(b)}
function Sb(){for(var a="",b=0;b<arguments.length;b++)a=ba(arguments[b])?a+Sb.apply(l,arguments[b]):"object"===typeof arguments[b]?a+ma(arguments[b]):a+arguments[b],a+=" ";return a}var Tb=l;function U(){if(Tb){var a=Sb.apply(l,arguments);Tb(a)}}function wb(){if("undefined"!==typeof console){var a=Sb.apply(l,arguments);console.log("FIREBASE INTERNAL ERROR: "+a)}}var Ma=/^[\-+]?[0-9]*\.?[0-9]+$/;
function ib(a){if("complete"===document.readyState)a();else{var b=o,c=function(){document.body?b||(b=k,a()):setTimeout(c,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",c,o),window.addEventListener("load",c,o)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&c()},o),window.attachEvent("onload",c,o))}}function Na(a,b){return a!==b?a===l?-1:b===l?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}
var Ub=0;function V(a,b,c,d,e){this.Da=b;this.L=c;this.H=d;this.ua=e;this.Y={};this.jc=0;this.Va=[];this.ka=0;b=A(this.bc,this);c=A(this.Wb,this);d=A(this.Xb,this);e=A(this.Yb,this);this.oa=new vb(a,b,c,d,e)}V.prototype.Ia=function(a,b,c){var d=++this.jc;Vb(this,{rn:d,payload:a});var e=this,a=setTimeout(function(){var a=e.Y[d];a&&(delete e.Y[d],a.O&&a.O.Sa&&a.O.Sa())},45E3);this.Y[d]={O:{Ra:b,Sa:c},Hb:a}};V.prototype.sendRequest=V.prototype.Ia;w=V.prototype;
w.bc=function(a){if("rn"in a){var b=a.rn,c=this.Y[b];c&&(delete this.Y[b],clearTimeout(c.Hb),c.O&&c.O.Ra&&c.O.Ra(a.data))}else"error"in a&&f("A server-side error has occurred: "+a.error),this.Da&&this.Da(a)};w.Wb=function(a){U("Realtime connection established.");this.oa=a;this.ka=1;for(a=0;a<this.Va.length;a++)Vb(this,this.Va[a]);this.Va=l;this.L&&(this.L(),this.L=l)};w.Xb=function(){this.oa=l;0===this.ka?U("Realtime connection failed."):1===this.ka&&U("Realtime connection lost.");this.close()};
w.Yb=function(){U("Connection shutdown command received. Shutting down...");this.ua&&(this.ua(),this.ua=l);this.H=l;this.close()};function Vb(a,b){2===a.ka&&f("Connection has already been closed.");0===a.ka?a.Va.push(b):a.oa.send(b)}w.close=function(){if(2!==this.ka){U("Closing realtime connection.");this.ka=2;this.oa&&(this.oa.close(),this.oa=l);this.H&&(this.H(),this.H=l);for(var a in this.Y){var b=this.Y[a];delete this.Y[a];b!==l&&(b.O&&b.O.Sa&&b.O.Sa(),clearTimeout(b.Hb))}}};
V.prototype.close=V.prototype.close;function Wb(a,b){this.id=Xb++;this.jb={};this.C=[];this.Ea=0;this.nb={};this.pa=o;this.Xa=1E3;Yb(this,a,b)}var Xb=0;function Zb(a,b){a.q("Listen on "+b);a.jb[b]=k;a.pa&&a.Wa.Ia({action:"listen",path:b},l,function(){a.q("timed out on listen...")})}Wb.prototype.pc=function(a){this.q("Unlisten on "+a);delete this.jb[a];var b=this;this.pa&&this.Wa.Ia({action:"unlisten",path:a},l,function(){b.q("timed out on unlisten...")})};
Wb.prototype.v=function(a,b){this.nb[a]=b;this.q("onDisconnect",d);var c=this;if(this.pa){var d={action:"onDisconnect",path:a.toString(),data:b};this.Wa.Ia(d,function(a){"success"!==a.status&&f("onDisconnect failed: "+ma(a.data))},function(){c.q("timed out on onDisconnect...")})}};Wb.prototype.put=function(a,b,c,d){a={action:"put",path:a.toString(),data:b};y(d)&&(a.hash=d);this.q("put",a);this.C.push({Eb:a,B:c});this.Ea++;c=this.C.length-1;this.pa&&$b(this,c)};
function $b(a,b){var c=a.C[b].B;a.Wa.Ia(a.C[b].Eb,function(d){a.q("put response",d);delete a.C[b];a.Ea--;0===a.Ea&&(a.C=[]);c&&c(d.status)},function(){a.q("timed out on put...")})}
function Yb(a,b,c){var d=(new Date).getTime(),e=l;a.Wa=new V(b,function(b){a.q("handleServerMessage",b);"data"in b?c(b.data.path,b.data.data):"timestamp"in b?Ub=b.timestamp-(new Date).getTime():f("Unrecognized message returned from server: "+ma(b))},function(){a.pa=k;e=(new Date).getTime();for(var b in a.jb)Zb(a,b);for(b in a.nb)a.v(b,a.nb[b]);for(b=0;b<a.C.length;b++)a.C[b]&&$b(a,b)},function(){a.pa=o;ac(a);e&&(3E4<(new Date).getTime()-e&&(a.Xa=1E3),e=l);var g=Math.max(0,a.Xa-((new Date).getTime()-
d)),g=Math.random()*g;setTimeout(function(){Yb(a,b,c)},g);a.Xa=Math.min(3E4,1.3*a.Xa)},function(){f(Error("Firebase connection to "+b+" was forcefully killed by the server.  Will not attempt reconnect."))})}function ac(a){for(var b=0;b<a.C.length;b++){var c=a.C[b];c&&c.Eb.hash&&(c.B&&c.B("disconnect"),delete a.C[b],a.Ea--)}0===a.Ea&&(a.C=[])}Wb.prototype.q=function(){U(this.id+":",arguments)};function bc(a){this.i=J;this.n=a}function cc(a,b){var c=new W(a.n,b);return new P(a.i.e(b),c)}function X(a,b,c){a.i=a.i.wa(b,c)}function ec(a,b,c,d){for(var e=a.i.e(b),c=c.i.e(b),d=R(d,b),g=o,i=d;i!==l;){if(i.c()!==l){g=k;break}i=i.parent()}if(g)return o;d=fc(c,e,d);return d!==e?(a.i=a.i.wa(b,d),k):o}bc.prototype.w=function(){return cc(this,new E("/")).w()};
function fc(a,b,c){if(c.a())return a;if(c.c()!==l)return b;a=a||J;c.o(function(d){var d=d.name(),e=a.t(d),g=b.t(d),i=R(c,d),e=fc(e,g,i);a=a.p(d,e)});return a};function gc(a,b,c){this.j=a;this.$=[];this.ra=c;"default"===this.j.N()?this.d=b:(this.d=J,hc(this,b,ic(this,b,c)))}gc.prototype.addEventListener=function(a,b,c){this.$.push({type:a,xa:b});for(var d=ic(this,this.d,this.ra),e=0;e<d.length;e++)d[e].type===a&&c.push({xa:b,T:d[e].T,Ha:d[e].Ha})};gc.prototype.removeEventListener=function(a,b){for(var c=o,d=0;d<this.$.length;d++){var e=this.$[d];if(e.type===a&&e.xa===b){this.$.splice(d,1);c=k;break}}return{nc:c,Ab:0===this.$.length}};
function hc(a,b,c){var d=[],e=a.j;y(a.j.ja)&&d.push(function(a){return 0<=(a!==e.ja?a<e.ja?-1:1:0)});y(a.j.ca)&&d.push(function(a){return 0>=(a!==e.ca?a<e.ca?-1:1:0)});y(a.j.Z)&&d.push(function(a,b){return 0<=Na(b,e.Z)});y(a.j.da)&&d.push(function(a,b){return 0>=Na(b,e.da)});var g=l,i=l;if(y(a.j.X))if(y(a.j.Z)){if(g=jc(b,d,a.j.X,o)){var j=b.t(g).f();d.push(function(a,b){return b<j||b===j&&a<=g})}}else if(i=jc(b,d,a.j.X,k)){var n=b.t(i).f();d.push(function(a,b){return b>n||b===n&&a>=i})}for(var m=
[],r=[],u=[],B=[],s=0;s<c.length;s++){var F=c[s].type,p=c[s].T,t=p.name(),G=p.b;switch(F){case "child_added":kc(d,t,G)&&(a.d=a.d.p(t,G),r.push(p));break;case "child_removed":a.d.t(t).a()||(a.d=a.d.p(t,l),m.push(c[s]));break;case "child_changed":!a.d.t(t).a()&&kc(d,t,G)&&(a.d=a.d.p(t,G),B.push(p));break;case "child_moved":var F=!a.d.t(t).a(),ra=kc(d,t,G);F?ra?(a.d=a.d.p(t,G),u.push(p)):(p=a.j.path.k(t),m.push(new C("child_removed",new P(a.d.t(t),p))),a.d=a.d.p(t,l)):ra&&(a.d=a.d.p(t,G),r.push(p))}}var dc=
g||i;if(dc){var Fc=(s=i!==l)?a.d.wb():a.d.yb(),pb=o,qb=o;(s?b.ib:b.o).call(b,function(b,c){if(pb){var d=a.j.path.k(b);m.push(new C("child_removed",new P(a.d.t(b),d)));a.d=a.d.p(b,l)}else qb&&(d=a.j.path.k(b),r.push(new P(c,d)),a.d=a.d.p(b,c));b===Fc&&(qb=k);b===dc&&(pb=k);if(qb&&pb)return k})}for(s=0;s<r.length;s++)p=r[s],b=a.d.G(p.name(),p.b),m.push(new C("child_added",p,b));for(s=0;s<u.length;s++)p=u[s],b=a.d.G(p.name(),p.b),m.push(new C("child_moved",p,b));for(s=0;s<B.length;s++)p=B[s],b=a.d.G(p.name(),
p.b),m.push(new C("child_changed",p,b));u=o;!a.ra&&0<c.length&&"value"===c[c.length-1].type&&(u=a.ra=k);a.ra&&(0<m.length||u)&&m.push(new C("value",new P(a.d,a.j.path)));return m}function jc(a,b,c,d){var e=l;(d?a.ib:a.o).call(a,function(a,d){if(kc(b,a,d)&&(e=a,c--,0===c))return k});return e}function kc(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.f()))return o;return k}
function ic(a,b,c){var d=[];if(!b.Q()){var e=l;b.o(function(b,c){var j=a.j.path.k(b);d.push(new C("child_added",new P(c,j),e));e=b})}c&&d.push(new C("value",new P(b,a.j.path)));return d};function lc(a,b){this.lc=a;this.Db=b;this.ha=new bc(this);this.r=new bc(this);this.K=new bc(this);this.S=new Q;this.bb=new Q;this.U=new Q;this.F=new Q;this.lb=J;var c=this;this.ba=new Wb(a+"/"+b,function(a,b){mc(c,a,b)})}
function nc(a,b,c,d){var e=b.path.s,g=R(a.U,e),i=g.c();if(i===l){var i={M:{}},j=o;bb(g,function(a){a.c()&&a.c().la&&(j=k)});j||(i.la=oc(a,e.toString()),ab(g,function(a){a=a.c();a!==l&&a.la&&(a.la(),a.la=l)}));S(g,i)}var g=b.N(),n=i.M[g];n||(n=a.K.i.e(e),a=T(a.F,e),n=new gc(b,n,a),i.M[g]=n);b=[];n.addEventListener(c,d,b);pc(b)}
function qc(a,b,c,d){var e=b.path.s,g=R(a.U,e),i=g.c(),j;if(i!==l){if("default"!==b.N()){if(j=i.M[b.N()])j=j.removeEventListener(c,d),j.Ab&&delete i.M[b.N()]}else{var b=l,n=o,m;for(m in i.M)if(j=i.M[m].removeEventListener(c,d),j.nc){b=m;n=j.Ab;break}n&&delete i.M[b]}if(Ya(i.M)){if(i.la){var r=T(a.F,e);cb(g,function(b){b.la=oc(a,b.path().toString());r&&S(R(a.F,b.path()),k)});i.la()}S(g,l)}}}function oc(a,b){Zb(a.ba,b);return A(a.ba.pc,a.ba,b)}
function mc(a,b,c){if(9<=b.length&&b.lastIndexOf(".priority")===b.length-9)b=new E(b.substring(0,b.length-9)),c!==l&&Ma.test(c)&&(c=Number(c)),X(a.ha,b,a.ha.i.e(b).eb(c));else{b=new E(b);X(a.ha,b,La(c));var d=o;bb(R(a.U,b),function(a){a.c()&&a.c().zb&&(d=k)},k);if(!d&&(c=R(a.U,b).c()))c.zb=k}ec(a.r,b,a.ha,a.S)?rc(a,sc(a,b)):tc(a,b)}function uc(a,b){bb(R(a.U,b),function(a){if(a.c()&&a.c().zb)return k});return o}
function tc(a,b){var c=[],d=a.lb,e=a.K.i;a.lb=a.K.i;var g=d.e(b),i=e.e(b),j=vc(a,b,g,i,c),g=g.f()!==i.f();if(j||g)for(var n=g,m=R(a.U,b);m.parent()!==l;){var r=d.e(m.path()),u=e.e(m.path()),g=m.parent();if(g.c()){var B=g.path(),i=e.e(B),s=[],m=Ea(m.path()),B=new W(a,B.k(m));if(r.a())r=i.G(m,u),s.push(new C("child_added",new P(u,B),r));else if(u.a())s.push(new C("child_removed",new P(r,B)));else if(j&&(r=i.G(m,u),s.push(new C("child_changed",new P(u,B),r))),n)r=i.G(m,u),s.push(new C("child_moved",
new P(u,B),r)),j=k;T(a.F,g.path())&&(Ea(g.path())||a.name(),n=new W(a,g.path()),s.push(new C("value",new P(i,n))));c.push({path:g.path().toString(),Ma:s})}m=g;n=o}for(d=0;d<c.length;d++)if(s=a,e=c[d].Ma,n=new E(c[d].path),j=R(s.U,n).c(),j!==l){g=j.M;i=[];s=s.lb.e(n);n=h;for(n in g){u=j.M[n];B=s;r=e;m=i;"default"!==u.j.N()?r=hc(u,B,r):(u.d=B,u.ra=u.ra||0<r.length&&"value"===r[r.length-1].type);for(B=0;B<r.length;B++){var F=r[B],p=F.type;"value"===F.type&&!F.T.Na()?p+="("+F.T.w()+")":"value"!==F.type&&
(p+=" "+F.T.name());U(u.j.path.n.ba.id+":event:"+u.j.path.s+":"+u.j.N()+":"+p);for(p=0;p<u.$.length;p++){var t=u.$[p];r[B].type===t.type&&m.push({xa:t.xa,T:F.T,Ha:F.Ha})}}}pc(i)}}
function vc(a,b,c,d,e){var g;c===d&&(g=o);c.Q()&&d.Q()?g=c.c()!==d.c():c.Q()?(wc(a,b,J,d,e),g=k):d.Q()?(wc(a,b,c,J,e),g=k):g=wc(a,b,c,d,e);c=o;T(a.F,b)||(ab(R(a.U,b),function(b){if(!T(a.F,b.path())){var c=new W(a,b.path());e.push({path:b.path(),Ma:[new C("value",new P(J,c))]})}}),c=k,R(a.F,b).clear(),S(R(a.F,b),k));if(g||c)c=new W(a,b),e.push({path:b.toString(),Ma:[new C("value",new P(d,c))]});return g}
function wc(a,b,c,d,e){var g=o,i=[],j=!R(a.U,b).a(),n=[],m=[],r=[],u={},B={},s,F,p,t,G,ra;s=c.qa();p=sa(s);F=d.qa();for(t=sa(F);p!==l||t!==l;){c=p===l?1:t===l?-1:p.key===t.key?0:Ka({name:p.key,ea:p.value.f()},{name:t.key,ea:t.value.f()});if(0>c)g=u[p.key],y(g)?(r.push({vb:p,Ib:n[g]}),n[g]=l):(B[p.key]=m.length,m.push(p)),g=k,p=sa(s);else{if(0<c)g=B[t.key],y(g)?(r.push({vb:m[g],Ib:t}),m[g]=l):(u[t.key]=n.length,n.push(t)),g=k;else{c=b.k(t.key);if(ra=vc(a,c,p.value,t.value,e))G=d.G(t.key,t.value),p=
new W(a,c),i.push(new C("child_changed",new P(t.value,p),G)),g=k;p=sa(s)}t=sa(F)}if(!j&&g)return k}for(j=0;j<m.length;j++)if(u=m[j])c=b.k(u.key),p=new W(a,c),vc(a,c,u.value,J,e),i.push(new C("child_removed",new P(u.value,p)));for(j=0;j<n.length;j++)if(m=n[j])c=b.k(m.key),p=new W(a,c),G=d.G(m.key,m.value),vc(a,c,J,m.value,e),i.push(new C("child_added",new P(m.value,p),G));for(j=0;j<r.length;j++)m=r[j].vb,n=r[j].Ib,c=b.k(n.key),p=new W(a,c),G=d.G(n.key,n.value),i.push(new C("child_moved",new P(n.value,
p),G)),(ra=vc(a,c,m.value,n.value,e))&&i.push(new C("child_changed",new P(n.value,p),G));0<i.length&&e.push({path:b.toString(),Ma:i});return g}function pc(a){for(var b=0;b<a.length;b++){var c=a[b].xa;c(a[b].T,a[b].Ha)}}
lc.prototype.ab=function(a,b,c,d){c!==l&&Ma.test(c)&&(c=Number(c));this.q("set",{path:a.toString(),value:b});var e=ob(),g=this;S(R(this.S,a),e);X(this.r,a,La(b,c));b=this.r.i.e(a).w(k);xc(this,a,b,function(b){O("success"===b,"put failed.  WHAT TO DO!? WHAT TO DO!?");var b=R(g.S,a),c=b.c();O(c!==l,"setWithPriority: pendingSet should not be null.");c===e&&(S(b,l),uc(g,a)&&(ec(g.r,a,g.ha,g.S),b=sc(g,a),rc(g,b)));d&&d(k)});b=sc(this,a);yc(this,a);rc(this,b)};
function yc(a,b){var c=R(a.bb,b);bb(c,function(b){zc(a,b)});zc(a,c);ab(c,function(b){zc(a,b)})}function zc(a,b){var c=b.c();if(c!==l){for(var d=-1,e=0;e<c.length;e++)if(c[e].status===Ac)O(d===e-1,"All SENT items should be at beginning of queue."),d=e,c[e].status=Bc;else if(c[e].cb(),c[e].B){var g=T(a.F,b.path())?cc(a.K,b.path()):l;c[e].B(o,g)}-1===d?S(b,l):c.length=d+1}}var Ac=2,Bc=4;
function Cc(a,b,c,d){function e(){}a.q("transaction on "+b);var g=new W(a,b);g.mb("value",e);var c={Cb:b,update:c,B:d,Bb:ob(),Gb:0,cb:function(){g.kb("value",e)}},d=a.K,i=c.update(d.i.e(b).w());if(y(i)){Ta("transaction failed: Data returned ",i);var j=a.r.i.e(b).f();X(d,b,La(i,j));tc(a,b);c.status=1;b=R(a.bb,b);d=b.c()||[];d.push(c);S(b,d);Dc(a)}else c.cb(),c.B&&(a=T(a.F,b)?cc(a.K,b):l,c.B(o,a))}function Dc(a,b){var c=b||a.bb;b||Ec(a,c);c.a()||(c.c()!==l?Gc(a,c):c.o(function(b){Dc(a,b)}))}
function Gc(a,b){var c=Hc(a,b);if(0!==c.length){var d=b.path();if(c[0].status!==Ac&&c[0].status!==Bc){for(var e=0;e<c.length;e++)O(1===c[e].status,"tryToSendTransactionForNode_: items in queue should all be run."),c[e].status=Ac,c[e].Gb++;var g=a.r.i.e(d).hash();X(a.r,d,a.K.i.e(d));var i=a.r.i.e(d).w(k),j=ob();S(R(a.S,d),j);xc(a,d,i,function(g){a.q("transaction put response",{path:d.toString(),status:g});var i=R(a.S,d),r=i.c();O(r!==l,"tryToSendTransactionsForNode_: pendingSet should not be null.");
r===j&&(S(i,l),X(a.r,d,a.ha.i.e(d)));if("success"===g){for(e=0;e<c.length;e++)c[e].status=3,c[e].B&&(g=T(a.F,d),O(g,"Transaction completed successfully but we don't have data for this location!?"),g=cc(a.K,b.path()),c[e].B(k,g)),c[e].cb();Dc(a)}else if("datastale"===g||"disconnect"===g){if("datastale"===g)for(e=0;e<c.length;e++)c[e].status=c[e].status===Bc?5:1;else if("disconnect"===g)for(e=0;e<c.length;e++)c[e].status=6;g=sc(a,d);rc(a,g)}else O(o,"Got unexpected put response to transaction: "+g)},
g)}}}
function rc(a,b){var c=b.path();X(a.K,c,a.r.i.e(c));var d=Hc(a,b);if(0!==d.length){for(var e=a.K.i.e(c),g=0;g<d.length;g++){var i=Fa(c,d[g].Cb),j=o,n;O(i!==l,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[g].status)j=k,n="set";else if(6===d[g].status)j=k,n="disconnect";else if(1===d[g].status)if(25<=d[g].Gb)j=k,n="maxretry";else{var m=d[g].update(e.e(i).w());y(m)?(Ta("transaction failed: Data returned ",m),e=e.wa(i,La(m))):(j=k,n="nodata")}j&&(d[g].cb(),d[g].status=3,d[g].B&&
(j=new W(a,d[g].Cb),i=new P(e.e(i),j),d[g].B(o,i,n)))}d=a.r.i.e(c).f();X(a.K,c,e.eb(d));Dc(a)}tc(a,c)}function sc(a,b){for(var c,d=a.bb;(c=H(b))!==l&&d.c()===l;)d=R(d,c),b=I(b);return d}function Hc(a,b){var c=[];Ic(a,b,c);c.sort(function(a,b){return a.Bb-b.Bb});return c}function Ic(a,b,c){var d=b.c();if(d!==l)for(var e=0;e<d.length;e++)c.push(d[e]);b.o(function(b){Ic(a,b,c)})}
function Ec(a,b){var c=b.c();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;S(b,0<c.length?c:l)}b.o(function(b){Ec(a,b)})}w=lc.prototype;w.qb=function(a,b,c){var d=ob(),e=this;xc(this,a.toString()+"/.priority",b,function(b){var i=R(e.S,a),j=i.c();O(j!==l,"setPriority: pendingSet should not be null.");j===d&&(S(i,l),ec(e.r,a,e.ha,e.S),i=sc(e,a),rc(e,i));c&&c("success"===b)});S(R(this.S,a),d);X(this.r,a,cc(this.r,a).b.eb(b));rc(this,sc(this,a))};
w.$a=function(a,b){this.ba.v(a,b)};function xc(a,b,c,d,e){a.ba.put(b,c,d,e)}w.toString=function(){return"http://"+this.lc+"/"+Da(this.Db)};w.name=q("Db");w.q=function(){U(this.ba.id+":",arguments)};function Jc(){this.pb={}}Jc.xb=function(){return Jc.Qb||(Jc.Qb=new Jc)};function Y(a,b,c,d,e,g){this.path=a;this.X=b;this.Z=Ma.test(c)?Number(c):c;this.ja=d;this.da=Ma.test(e)?Number(e):e;this.ca=g;y(this.Z)&&y(this.da)&&y(this.X)&&f("firebase.Query: Can't combine startAt(), endAt(), and limit().")}Y.prototype.mb=function(a,b){L("firebase.Query.on",2,2,arguments.length);Va("firebase.Query.on",a);N("firebase.Query.on",2,b,o);nc(this.path.n,this,a,b);return b};Y.prototype.on=Y.prototype.mb;
Y.prototype.kb=function(a,b){L("firebase.Query.off",2,2,arguments.length);Va("firebase.Query.off",a);N("firebase.Query.off",2,b,o);qc(this.path.n,this,a,b)};Y.prototype.off=Y.prototype.kb;Y.prototype.fc=function(a,b){function c(g){e&&(e=o,d.kb(a,c),b(g))}L("firebase.Query.once",2,2,arguments.length);Va("firebase.Query.once",a);N("firebase.Query.once",2,b,o);var d=this,e=k;this.mb(a,c)};Y.prototype.once=Y.prototype.fc;
Y.prototype.Rb=function(a){L("firebase.Query.limit",1,1,arguments.length);(!ca(a)||Math.floor(a)!==a||0>=a)&&f("firebase.Query.limit: First argument must be a positive integer.");return new Y(this.path,a,this.Z,this.ja,this.da,this.ca)};Y.prototype.limit=Y.prototype.Rb;Y.prototype.mc=function(a,b){L("firebase.Query.startAt",0,2,arguments.length);Ua("firebase.Query.startAt",1,a,k);Wa("firebase.Query.startAt",b);y(a)||(b=a=l);return new Y(this.path,this.X,a,b,this.da,this.ca)};Y.prototype.startAt=Y.prototype.mc;
Y.prototype.Mb=function(a,b){L("firebase.Query.endAt",0,2,arguments.length);Ua("firebase.Query.endAt",1,a,k);Wa("firebase.Query.endAt",b);return new Y(this.path,this.X,this.Z,this.ja,a,b)};Y.prototype.endAt=Y.prototype.Mb;Y.prototype.N=function(){var a=[];y(this.Z)&&a.push({sp:this.Z});y(this.ja)&&a.push({sn:this.ja});y(this.da)&&a.push({ep:this.da});y(this.ca)&&a.push({en:this.ca});y(this.X)&&a.push({l:this.X});return 0===a.length?"default":ma(a)};var Kc=function(){var a=0,b=[];return function(){var c=(new Date).getTime()+Ub,d=c===a;a=c;for(var e=Array(8),g=7;0<=g;g--)e[g]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(c%64),c=Math.floor(c/64);O(0===c);c=e.join("");if(d){for(g=11;0<=g&&63===b[g];g--)b[g]=0;b[g]++}else for(g=0;12>g;g++)b[g]=Math.floor(64*Math.random());for(g=0;12>g;g++)c+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(b[g]);O(20===c.length,"NextPushId: Length should be 20.");
return c}}();function W(){var a,b,c;Y.call(this,this);if(arguments[0]instanceof lc)this.n=arguments[0],this.s=arguments[1];else{L("new Firebase",1,1,arguments.length);a=arguments[0];var d="";c=b="";if(z(a)){var e=a.indexOf("://");0<e&&(a=a.substring(e+3));e=a.indexOf("/");0<e&&(d=a.substring(0,e),a=a.substring(e+1),e=a.indexOf("/"),0<e?(b=a.substring(0,e),c=a.substring(e)):(b=a,c="/"))}a=d;c=new E(c);d=c.toString();(!z(a)||0===a.length||!Ra(b)||0!==d.length&&(!z(d)||0===d.length||Qa.test(d)))&&f(Error(M("new Firebase",
1,o)+"must be a valid firebase URL."));var d=Jc.xb(),e=a+"/"+b,g=d.pb[e];g||(g=new lc(a,b),d.pb[e]=g);this.n=g;this.s=c}}fa(W,Y);var Lc=W,Mc=["Firebase"],Z=x;!(Mc[0]in Z)&&Z.execScript&&Z.execScript("var "+Mc[0]);for(var Nc;Mc.length&&(Nc=Mc.shift());)!Mc.length&&y(Lc)?Z[Nc]=Lc:Z=Z[Nc]?Z[Nc]:Z[Nc]={};W.prototype.name=function(){L("Firebase.name",0,0,arguments.length);return this.s.a()?this.n.name():Ea(this.s)};W.prototype.name=W.prototype.name;
W.prototype.k=function(a){L("Firebase.child",1,1,arguments.length);ca(a)?a=""+a:a instanceof E||Xa("Firebase.child",a);return new W(this.n,this.s.k(a))};W.prototype.child=W.prototype.k;W.prototype.parent=function(){L("Firebase.parent",0,0,arguments.length);var a=this.s.parent();return a===l?l:new W(this.n,a)};W.prototype.parent=W.prototype.parent;W.prototype.toString=function(){L("Firebase.toString",0,0,arguments.length);return this.parent()===l?this.n.toString():this.parent().toString()+"/"+Da(this.name())};
W.prototype.toString=W.prototype.toString;W.prototype.set=function(a,b){L("Firebase.set",1,2,arguments.length);Sa("Firebase.set",a,o);N("Firebase.set",2,b,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.set failed: "+this.name()+" is a read-only object.");return this.n.ab(this.s,a,l,b)};W.prototype.set=W.prototype.set;
W.prototype.ab=function(a,b,c){L("Firebase.setWithPriority",2,3,arguments.length);Sa("Firebase.setWithPriority",a,o);Ua("Firebase.setWithPriority",2,b,o);N("Firebase.setWithPriority",3,c,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.n.ab(this.s,a,b,c)};W.prototype.setWithPriority=W.prototype.ab;
W.prototype.remove=function(a){L("Firebase.remove",0,1,arguments.length);N("Firebase.remove",1,a,k);this.set(l,a)};W.prototype.remove=W.prototype.remove;W.prototype.transaction=function(a,b){L("Firebase.transaction",1,2,arguments.length);N("Firebase.transaction",1,a,o);N("Firebase.transaction",2,b,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.transaction failed: "+this.name()+" is a read-only object.");Cc(this.n,this.s,a,b)};W.prototype.transaction=W.prototype.transaction;
W.prototype.qb=function(a,b){L("Firebase.setPriority",1,2,arguments.length);Ua("Firebase.setPriority",1,a,o);N("Firebase.setPriority",2,b,k);a!==l&&Ma.test(a)&&(a=Number(a));this.n.qb(this.s,a,b)};W.prototype.setPriority=W.prototype.qb;W.prototype.push=function(a,b){L("Firebase.push",0,2,arguments.length);Sa("Firebase.push",a,k);N("Firebase.push",2,b,k);var c=this.k(Kc());"undefined"!==typeof a&&a!==l&&c.set(a,b);return c};W.prototype.push=W.prototype.push;
W.prototype.hc=function(){L("Firebase.removeOnDisconnect",0,0,arguments.length);this.n.$a(this.s,l)};W.prototype.removeOnDisconnect=W.prototype.hc;W.prototype.$a=function(a){L("Firebase.setOnDisconnect",1,1,arguments.length);Sa("Firebase.setOnDisconnect",a,o);this.n.$a(this.s,a)};W.prototype.setOnDisconnect=W.prototype.$a;W.enableLogging=function(a){a===k?"undefined"!==typeof console&&(Tb=A(console.log,console)):Tb=a?a:l};var $={};W.TEST_HOOKS=$;$.ic=function(){return Jc.xb().pb};$.repos=$.ic;
$.Pb=function(a){var b=K.prototype.hash;K.prototype.hash=a;return function(){K.prototype.hash=b}};$.hijackHash=$.Pb;$.N=function(a){return a.N()};$.queryIdentifier=$.N;$.Kb=V;$.RealTimeConnection=$.Kb;})();